# Generated by Django 4.1 on 2023-03-02 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70, null=True, verbose_name='Título')),
                ('descriçao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membros do Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('descriçao', models.CharField(max_length=100, null=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa Prioridade'), ('Média', 'Média Prioridade'), ('Alta', 'Alta Prioridade')], max_length=5, verbose_name='Prioridade')),
                ('membros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
        ),
    ]
