# Generated by Django 4.1 on 2023-03-10 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='projetos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectos.projetos', verbose_name='Adicionar Projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
    ]
