# Generated by Django 4.1 on 2023-03-10 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0002_cards_projetos_alter_projetos_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='data_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
