# Generated by Django 4.1 on 2023-06-14 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0002_list_alter_projetos_data_registro_delete_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 13, 21, 5, 41, 248146)),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_registro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 13, 21, 5, 41, 247142)),
        ),
    ]
