# Generated by Django 4.1 on 2023-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0003_projetos_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descriçao',
            field=models.CharField(max_length=36, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(max_length=21, null=True, verbose_name='Título'),
        ),
    ]
