# Generated by Django 4.1 on 2023-06-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectos', '0003_alter_list_data_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
