# Generated by Django 4.1 on 2023-03-27 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectos', '0004_alter_projetos_data_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='membros',
        ),
        migrations.AddField(
            model_name='cards',
            name='criador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
