# Generated by Django 4.1 on 2023-02-26 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, null=True)),
                ('cpf', models.CharField(max_length=17, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=16, null=True)),
                ('endereço', models.CharField(max_length=150, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('pais', models.CharField(max_length=20, null=True, verbose_name='País')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Foto de Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
