# Generated by Django 4.1 on 2023-03-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_nome_completo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Welcome',
        ),
    ]
