# Generated by Django 4.1 on 2023-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='descriçao',
            field=models.CharField(max_length=20, null=True, verbose_name='Descrição do Negócio'),
        ),
    ]
