# Generated by Django 4.1 on 2023-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='ticket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ticket do Negócio'),
        ),
    ]
