# Generated by Django 4.1 on 2023-04-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtdClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.negocio')),
            ],
        ),
    ]
