# Generated by Django 4.1 on 2023-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_negocio_descriçao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='descriçao',
            field=models.CharField(max_length=30, null=True, verbose_name='Descrição do Negócio'),
        ),
    ]
