# Generated by Django 4.1 on 2023-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_negocio_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='cliente',
            field=models.CharField(max_length=18, null=True, verbose_name='Cliente'),
        ),
    ]
